title: Bloggers Tech
author: Charlie Phresh
email: your-email@domain.com
description: This is my blog website for tech vibes.
theme: minima

# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  your-github-handle # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
